/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Annotation {
  'id' : bigint,
  'fillColor' : [] | [string],
  'imageData' : [] | [string],
  'endX' : [] | [number],
  'endY' : [] | [number],
  'pageNumber' : bigint,
  'timestamp' : bigint,
  'pdfId' : bigint,
  'annotationType' : string,
  'shapeType' : [] | [string],
  'coordinates' : string,
}
export type AnnotationCreateResult = { 'error' : string } |
  { 'success' : null };
export type AnnotationDeleteResult = { 'error' : string } |
  { 'success' : null };
export type AnnotationUpdateResult = { 'error' : string } |
  { 'success' : null };
export type BillingCycle = { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'halfYearly' : null } |
  { 'yearly' : null };
export interface PdfMetadata {
  'id' : bigint,
  'title' : string,
  'contentBase64' : string,
  'assignedFaculty' : Array<string>,
  'isTaught' : boolean,
}
export type PlanTier = { 'premium' : null } |
  { 'diamond' : null } |
  { 'basic' : null };
export type PriceList = Array<
  {
    'maxFaculty' : bigint,
    'tier' : PlanTier,
    'cycle' : BillingCycle,
    'maxPdfLimit' : bigint,
    'maxLicenses' : bigint,
    'priceInr' : bigint,
  }
>;
export interface SubscriptionPlan {
  'maxFaculty' : bigint,
  'tier' : PlanTier,
  'cycle' : BillingCycle,
  'maxPdfLimit' : bigint,
  'maxLicenses' : bigint,
  'priceInr' : bigint,
}
export type SyncResult = { 'error' : string } |
  { 'success' : SyncState };
export interface SyncState {
  'unsyncedChanges' : bigint,
  'lastSyncTimestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnotation' : ActorMethod<[Annotation], AnnotationCreateResult>,
  'addPdf' : ActorMethod<[PdfMetadata], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnotation' : ActorMethod<[bigint], AnnotationDeleteResult>,
  'getActiveSubscriptionPlan' : ActorMethod<[], SubscriptionPlan>,
  'getAvailablePriceList' : ActorMethod<[], PriceList>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentSubscriptionLimits' : ActorMethod<
    [],
    { 'maxFaculty' : bigint, 'maxPdfLimit' : bigint, 'maxLicenses' : bigint }
  >,
  'getPdfById' : ActorMethod<[bigint], [] | [PdfMetadata]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPdfAsTaught' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'syncAnnotations' : ActorMethod<[], SyncResult>,
  'updateAnnotation' : ActorMethod<[Annotation], AnnotationUpdateResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];