/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Annotation {
  'fillColor' : [] | [string],
  'imageData' : [] | [string],
  'endX' : [] | [number],
  'endY' : [] | [number],
  'pageNumber' : bigint,
  'timestamp' : bigint,
  'pdfId' : bigint,
  'annotationType' : string,
  'shapeType' : [] | [string],
  'coordinates' : string,
}
export interface Faculty { 'id' : bigint, 'active' : boolean, 'name' : string }
export type FacultyCreateResult = { 'error' : string } |
  { 'limitReached' : bigint } |
  { 'success' : null };
export interface FacultyWithPdfCount {
  'faculty' : Faculty,
  'pdfCount' : bigint,
}
export interface PDF {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'taught' : boolean,
  'uploadDate' : bigint,
  'facultyIds' : Array<bigint>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFaculty' : ActorMethod<[string], FacultyCreateResult>,
  'getAllFacultyWithPdfCount' : ActorMethod<[], Array<FacultyWithPdfCount>>,
  'getAnnotationsByPDF' : ActorMethod<[bigint], Array<Annotation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFaculty' : ActorMethod<[], Array<Faculty>>,
  'getPDFsByFaculty' : ActorMethod<[bigint], Array<PDF>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsTaught' : ActorMethod<[bigint], undefined>,
  'resetAdminCredentials' : ActorMethod<[], boolean>,
  'saveAnnotation' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      [] | [number],
      [] | [number],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminCredentials' : ActorMethod<[string, string], boolean>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];