/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Annotation = IDL.Record({
  'id' : IDL.Nat,
  'fillColor' : IDL.Opt(IDL.Text),
  'imageData' : IDL.Opt(IDL.Text),
  'endX' : IDL.Opt(IDL.Float64),
  'endY' : IDL.Opt(IDL.Float64),
  'pageNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'pdfId' : IDL.Nat,
  'annotationType' : IDL.Text,
  'shapeType' : IDL.Opt(IDL.Text),
  'coordinates' : IDL.Text,
});
export const AnnotationCreateResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnotationDeleteResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SyncState = IDL.Record({
  'unsyncedChanges' : IDL.Nat,
  'lastSyncTimestamp' : IDL.Int,
});
export const SyncResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : SyncState,
});
export const AnnotationUpdateResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnotation' : IDL.Func([Annotation], [AnnotationCreateResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnotation' : IDL.Func([IDL.Nat], [AnnotationDeleteResult], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncAnnotations' : IDL.Func([], [SyncResult], []),
  'updateAnnotation' : IDL.Func([Annotation], [AnnotationUpdateResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Annotation = IDL.Record({
    'id' : IDL.Nat,
    'fillColor' : IDL.Opt(IDL.Text),
    'imageData' : IDL.Opt(IDL.Text),
    'endX' : IDL.Opt(IDL.Float64),
    'endY' : IDL.Opt(IDL.Float64),
    'pageNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'pdfId' : IDL.Nat,
    'annotationType' : IDL.Text,
    'shapeType' : IDL.Opt(IDL.Text),
    'coordinates' : IDL.Text,
  });
  const AnnotationCreateResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnotationDeleteResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SyncState = IDL.Record({
    'unsyncedChanges' : IDL.Nat,
    'lastSyncTimestamp' : IDL.Int,
  });
  const SyncResult = IDL.Variant({ 'error' : IDL.Text, 'success' : SyncState });
  const AnnotationUpdateResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnotation' : IDL.Func([Annotation], [AnnotationCreateResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnotation' : IDL.Func([IDL.Nat], [AnnotationDeleteResult], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncAnnotations' : IDL.Func([], [SyncResult], []),
    'updateAnnotation' : IDL.Func([Annotation], [AnnotationUpdateResult], []),
  });
};

export const init = ({ IDL }) => { return []; };