/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FacultyCreateResult = IDL.Variant({
  'error' : IDL.Text,
  'limitReached' : IDL.Nat,
  'success' : IDL.Null,
});
export const Faculty = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
});
export const FacultyWithPdfCount = IDL.Record({
  'faculty' : Faculty,
  'pdfCount' : IDL.Nat,
});
export const Annotation = IDL.Record({
  'fillColor' : IDL.Opt(IDL.Text),
  'imageData' : IDL.Opt(IDL.Text),
  'endX' : IDL.Opt(IDL.Float64),
  'endY' : IDL.Opt(IDL.Float64),
  'pageNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'pdfId' : IDL.Nat,
  'annotationType' : IDL.Text,
  'shapeType' : IDL.Opt(IDL.Text),
  'coordinates' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PDF = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'taught' : IDL.Bool,
  'uploadDate' : IDL.Int,
  'facultyIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFaculty' : IDL.Func([IDL.Text], [FacultyCreateResult], []),
  'getAllFacultyWithPdfCount' : IDL.Func(
      [],
      [IDL.Vec(FacultyWithPdfCount)],
      ['query'],
    ),
  'getAnnotationsByPDF' : IDL.Func([IDL.Nat], [IDL.Vec(Annotation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFaculty' : IDL.Func([], [IDL.Vec(Faculty)], ['query']),
  'getPDFsByFaculty' : IDL.Func([IDL.Nat], [IDL.Vec(PDF)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsTaught' : IDL.Func([IDL.Nat], [], []),
  'resetAdminCredentials' : IDL.Func([], [IDL.Bool], []),
  'saveAnnotation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FacultyCreateResult = IDL.Variant({
    'error' : IDL.Text,
    'limitReached' : IDL.Nat,
    'success' : IDL.Null,
  });
  const Faculty = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  const FacultyWithPdfCount = IDL.Record({
    'faculty' : Faculty,
    'pdfCount' : IDL.Nat,
  });
  const Annotation = IDL.Record({
    'fillColor' : IDL.Opt(IDL.Text),
    'imageData' : IDL.Opt(IDL.Text),
    'endX' : IDL.Opt(IDL.Float64),
    'endY' : IDL.Opt(IDL.Float64),
    'pageNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'pdfId' : IDL.Nat,
    'annotationType' : IDL.Text,
    'shapeType' : IDL.Opt(IDL.Text),
    'coordinates' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PDF = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'taught' : IDL.Bool,
    'uploadDate' : IDL.Int,
    'facultyIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFaculty' : IDL.Func([IDL.Text], [FacultyCreateResult], []),
    'getAllFacultyWithPdfCount' : IDL.Func(
        [],
        [IDL.Vec(FacultyWithPdfCount)],
        ['query'],
      ),
    'getAnnotationsByPDF' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Annotation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFaculty' : IDL.Func([], [IDL.Vec(Faculty)], ['query']),
    'getPDFsByFaculty' : IDL.Func([IDL.Nat], [IDL.Vec(PDF)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsTaught' : IDL.Func([IDL.Nat], [], []),
    'resetAdminCredentials' : IDL.Func([], [IDL.Bool], []),
    'saveAnnotation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };