/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AnnotationUpdateResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
};
export type AnnotationDeleteResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
};
export interface PdfMetadata {
    id: bigint;
    title: string;
    contentBase64: string;
    assignedFaculty: Array<string>;
    isTaught: boolean;
}
export type PriceList = Array<{
    maxFaculty: bigint;
    tier: PlanTier;
    cycle: BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}>;
export interface Annotation {
    id: bigint;
    fillColor?: string;
    imageData?: string;
    endX?: number;
    endY?: number;
    pageNumber: bigint;
    timestamp: bigint;
    pdfId: bigint;
    annotationType: string;
    shapeType?: string;
    coordinates: string;
}
export type SyncResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: SyncState;
};
export interface SubscriptionPlan {
    maxFaculty: bigint;
    tier: PlanTier;
    cycle: BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}
export type AnnotationCreateResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
};
export interface UserProfile {
    name: string;
}
export interface SyncState {
    unsyncedChanges: bigint;
    lastSyncTimestamp: bigint;
}
export enum BillingCycle {
    quarterly = "quarterly",
    monthly = "monthly",
    halfYearly = "halfYearly",
    yearly = "yearly"
}
export enum PlanTier {
    premium = "premium",
    diamond = "diamond",
    basic = "basic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnotation(annotation: Annotation): Promise<AnnotationCreateResult>;
    addPdf(pdf: PdfMetadata): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAnnotation(_annotationId: bigint): Promise<AnnotationDeleteResult>;
    getActiveSubscriptionPlan(): Promise<SubscriptionPlan>;
    getAvailablePriceList(): Promise<PriceList>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentSubscriptionLimits(): Promise<{
        maxFaculty: bigint;
        maxPdfLimit: bigint;
        maxLicenses: bigint;
    }>;
    getPdfById(pdfId: bigint): Promise<PdfMetadata | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markPdfAsTaught(pdfId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSubscriptionPlan(newPlan: SubscriptionPlan): Promise<void>;
    syncAnnotations(): Promise<SyncResult>;
    updateAnnotation(_annotation: Annotation): Promise<AnnotationUpdateResult>;
}
import type { Annotation as _Annotation, AnnotationCreateResult as _AnnotationCreateResult, AnnotationDeleteResult as _AnnotationDeleteResult, AnnotationUpdateResult as _AnnotationUpdateResult, BillingCycle as _BillingCycle, PdfMetadata as _PdfMetadata, PlanTier as _PlanTier, PriceList as _PriceList, SubscriptionPlan as _SubscriptionPlan, SyncResult as _SyncResult, SyncState as _SyncState, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnotation(arg0: Annotation): Promise<AnnotationCreateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnotation(to_candid_Annotation_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnnotationCreateResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnotation(to_candid_Annotation_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnnotationCreateResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPdf(arg0: PdfMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPdf(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPdf(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAnnotation(arg0: bigint): Promise<AnnotationDeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnotation(arg0);
                return from_candid_AnnotationDeleteResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnotation(arg0);
            return from_candid_AnnotationDeleteResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveSubscriptionPlan(): Promise<SubscriptionPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSubscriptionPlan();
                return from_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSubscriptionPlan();
            return from_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailablePriceList(): Promise<PriceList> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailablePriceList();
                return from_candid_PriceList_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailablePriceList();
            return from_candid_PriceList_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentSubscriptionLimits(): Promise<{
        maxFaculty: bigint;
        maxPdfLimit: bigint;
        maxLicenses: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentSubscriptionLimits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentSubscriptionLimits();
            return result;
        }
    }
    async getPdfById(arg0: bigint): Promise<PdfMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markPdfAsTaught(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markPdfAsTaught(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPdfAsTaught(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setSubscriptionPlan(arg0: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubscriptionPlan(to_candid_SubscriptionPlan_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubscriptionPlan(to_candid_SubscriptionPlan_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async syncAnnotations(): Promise<SyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.syncAnnotations();
                return from_candid_SyncResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncAnnotations();
            return from_candid_SyncResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnnotation(arg0: Annotation): Promise<AnnotationUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnotation(to_candid_Annotation_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnnotationUpdateResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnotation(to_candid_Annotation_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnnotationUpdateResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnnotationCreateResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnotationCreateResult): AnnotationCreateResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_AnnotationDeleteResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnotationDeleteResult): AnnotationDeleteResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_AnnotationUpdateResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnotationUpdateResult): AnnotationUpdateResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BillingCycle_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingCycle): BillingCycle {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlanTier_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanTier): PlanTier {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PriceList_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceList): PriceList {
    return from_candid_vec_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SyncResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyncResult): SyncResult {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PdfMetadata]): PdfMetadata | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxFaculty: bigint;
    tier: _PlanTier;
    cycle: _BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}): {
    maxFaculty: bigint;
    tier: PlanTier;
    cycle: BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
} {
    return {
        maxFaculty: value.maxFaculty,
        tier: from_candid_PlanTier_n10(_uploadFile, _downloadFile, value.tier),
        cycle: from_candid_BillingCycle_n12(_uploadFile, _downloadFile, value.cycle),
        maxPdfLimit: value.maxPdfLimit,
        maxLicenses: value.maxLicenses,
        priceInr: value.priceInr
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    diamond: null;
} | {
    basic: null;
}): PlanTier {
    return "premium" in value ? PlanTier.premium : "diamond" in value ? PlanTier.diamond : "basic" in value ? PlanTier.basic : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    yearly: null;
}): BillingCycle {
    return "quarterly" in value ? BillingCycle.quarterly : "monthly" in value ? BillingCycle.monthly : "halfYearly" in value ? BillingCycle.halfYearly : "yearly" in value ? BillingCycle.yearly : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: _SyncState;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: SyncState;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: null;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    maxFaculty: bigint;
    tier: _PlanTier;
    cycle: _BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}>): Array<{
    maxFaculty: bigint;
    tier: PlanTier;
    cycle: BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}> {
    return value.map((x)=>from_candid_record_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Annotation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Annotation): _Annotation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BillingCycle_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingCycle): _BillingCycle {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_PlanTier_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): _PlanTier {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fillColor?: string;
    imageData?: string;
    endX?: number;
    endY?: number;
    pageNumber: bigint;
    timestamp: bigint;
    pdfId: bigint;
    annotationType: string;
    shapeType?: string;
    coordinates: string;
}): {
    id: bigint;
    fillColor: [] | [string];
    imageData: [] | [string];
    endX: [] | [number];
    endY: [] | [number];
    pageNumber: bigint;
    timestamp: bigint;
    pdfId: bigint;
    annotationType: string;
    shapeType: [] | [string];
    coordinates: string;
} {
    return {
        id: value.id,
        fillColor: value.fillColor ? candid_some(value.fillColor) : candid_none(),
        imageData: value.imageData ? candid_some(value.imageData) : candid_none(),
        endX: value.endX ? candid_some(value.endX) : candid_none(),
        endY: value.endY ? candid_some(value.endY) : candid_none(),
        pageNumber: value.pageNumber,
        timestamp: value.timestamp,
        pdfId: value.pdfId,
        annotationType: value.annotationType,
        shapeType: value.shapeType ? candid_some(value.shapeType) : candid_none(),
        coordinates: value.coordinates
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxFaculty: bigint;
    tier: PlanTier;
    cycle: BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
}): {
    maxFaculty: bigint;
    tier: _PlanTier;
    cycle: _BillingCycle;
    maxPdfLimit: bigint;
    maxLicenses: bigint;
    priceInr: bigint;
} {
    return {
        maxFaculty: value.maxFaculty,
        tier: to_candid_PlanTier_n22(_uploadFile, _downloadFile, value.tier),
        cycle: to_candid_BillingCycle_n24(_uploadFile, _downloadFile, value.cycle),
        maxPdfLimit: value.maxPdfLimit,
        maxLicenses: value.maxLicenses,
        priceInr: value.priceInr
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): {
    premium: null;
} | {
    diamond: null;
} | {
    basic: null;
} {
    return value == PlanTier.premium ? {
        premium: null
    } : value == PlanTier.diamond ? {
        diamond: null
    } : value == PlanTier.basic ? {
        basic: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingCycle): {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    yearly: null;
} {
    return value == BillingCycle.quarterly ? {
        quarterly: null
    } : value == BillingCycle.monthly ? {
        monthly: null
    } : value == BillingCycle.halfYearly ? {
        halfYearly: null
    } : value == BillingCycle.yearly ? {
        yearly: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
